pipeline {
    agent any

    stages {
        stage('Checkout Ansible code') {
            steps {
                script {
                    git branch: 'main', url: 'https://github.com/alexfbasa/AnsibleZabbix.git'
                }
            }
        }

        stage('Run Ansible playbook') {
            steps {
                script {
                    ansiblePlaybook(
                        playbook: 'playbooks/install_zabbix_agent.yml',
                        inventory: 'inventories/inventory.yaml',
                        extraVars: [
                            zabbix_server_ip: 'grafana-zabbix.dev',
                            zabbix_agent_hostname: 'postgres.dev'
                        ],
                        credentialsId: 'ansible_key'
                    )
                }
            }
        }
    }
}
