pipeline {
    agent {
        docker {
            image 'debian:12'
        }
    }
    stages {
        stage('Print Workspace Path') {
            steps {
                echo "Jenkins Workspace Path: ${WORKSPACE}"
            }
        }
        stage('Checkout Ansible code') {
            steps {
                script {
                    git branch: 'master', url: 'https://github.com/alexfbasa/AnsibleZabbix.git'
                }
            }
        }

        stage('Run Ansible playbook') {
            steps {
                script {
                    sh 'ansible-playbook -i inventories/inventory.yaml playbooks/install_zabbix_agent.yml'
                }
            }
        }

        stage('Run Python script') {
            steps {
                script {
                    sh 'pip3 install pyzabbix'
                    sh 'docker run -v ${WORKSPACE}:/workspace -w /workspace debian:12 python3 scripts/provision_zabbix_host.py'
                }
            }
        }
    }
}
