pipeline {
    agent any

    stages {
        stage('Print Workspace Path') {
            steps {
                echo "Jenkins Workspace Path: ${WORKSPACE}"
            }
        }
        stage('Install Zabbix Collection') {
            steps {
                script {
                    sh 'ansible-galaxy collection install community.zabbix'
                }
            }
        }
        stage('Checkout Ansible code') {
            steps {
                script {
                    git branch: 'master', url: 'https://github.com/alexfbasa/AnsibleZabbix.git'
                }
            }
        }

        stage('Run Ansible playbook') {
            steps {
                script {
                    ansiblePlaybook(
                        playbook: 'playbooks/install_zabbix_agent.yml',
                        inventory: 'inventories/inventory.yaml',
                        credentialsId: 'ansible_key'
                    )
                }
            }
        }
    }
}
