---
- name: Install Zabbix Agent
  hosts: all
  become: yes

  tasks:
    - name: Install Zabbix Agent
      ansible.builtin.yum:
        name: zabbix-agent
        state: present

    - name: Start Zabbix Service
      ansible.builtin.service:
        name: zabbix-agent
        enabled: yes
