---
- name: Install Zabbix Agent and configure host
  hosts: all
  become: yes

  tasks:
    - name: Install Zabbix Agent
      ansible.builtin.yum:
        name: zabbix-agent
        state: present

    - name: Print current working directory
      command: pwd
      register: pwd_output

    - debug:
        var: pwd_output.stdout_lines

    - name: Debug - Print Zabbix Agent config content
      command: cat ../templates/zabbix_agent.conf.j2
      register: template_content

    - debug:
        var: template_content.stdout_lines

    - name: Start Zabbix Service
      ansible.builtin.service:
        name: zabbix-agent
        enabled: yes

  handlers:
    - name: restart zabbix-agent
      service:
        name: zabbix-agent
        state: restarted
