---
- name: Configure Zabbix Host
  hosts: localhost
  gather_facts: false

  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 8080
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: ""

  tasks:
    - name: Install Zabbix Agent
      ansible.builtin.yum:
        name: zabbix-agent
        state: present
      when: ansible_facts.pkg_mgr == 'yum'


    - name: Create a new host in Zabbix
      community.zabbix.zabbix_host:
        host_name: "{{ inventory_hostname }}"
        visible_name: "{{ inventory_hostname }}"
        description: "Zabbix Host for {{ inventory_hostname }}"
        host_groups:
          - Linux Servers
        link_templates:
          - Template OS Linux
        status: enabled
        state: present
        inventory_mode: manual

    - name: Start Zabbix Agent
      ansible.builtin.service:
        name: zabbix-agent
        state: started
        enabled: yes
