---
- name: Install Zabbix Agent and configure host
  hosts: all
  become: yes

  tasks:
    - name: Install Zabbix Agent
      yum:
        name: zabbix-agent
        state: present

    - name: Copy Zabbix Agent configuration file
      template:
        src: zabbix_agent.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
      notify:
        - restart zabbix-agent

  handlers:
    - name: restart zabbix-agent
      service:
        name: zabbix-agent
        state: restarted
