---
- name: Install Zabbix Agent and Configure Monitored Host
  hosts: all
  become: yes

  tasks:
    - name: Install Zabbix Agent
      ansible.builtin.yum:
        name: zabbix-agent
        state: present

    - name: Start Zabbix Service
      ansible.builtin.service:
        name: zabbix-agent
        enabled: yes

    - name: Register Host in Zabbix
      community.zabbix.zabbix_host:
        server_url: "http://172.17.8.103:8080/zabbix"
        login_user: "admin"
        login_password: "admin_password"
        host_name: "{{ inventory_hostname }}"
        visible_name: "{{ inventory_hostname }}"
        groups:
          - name: "Linux Servers"
        templates:
          - name: "Template OS Linux"
        state: present
