---
- name: Install Zabbix Agent and configure host
  hosts: all
  become: yes

  tasks:
    - name: Install Zabbix Agent
      ansible.builtin.yum:
        name: zabbix-agent
        state: present

    - name: Copy Zabbix Agent configuration file
      template:
        src: templates/zabbix_agent.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
      notify:
        - restart zabbix-agent

    - name: Start Zabbix Service
      ansible.builtin.service:
        name: zabbix-agent
        enabled: yes

  handlers:
    - name: restart zabbix-agent
      ansible.builtin.service:
        name: zabbix-agent
        state: restarted
