---
- name: Install Zabbix Agent
  hosts: postgres.dev
  become: yes

  tasks:
    - name: Add Zabbix repository
      yum_repository:
        name: zabbix
        description: Zabbix Official Repository
        baseurl: https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/
        gpgcheck: yes
        gpgkey: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX
        enabled: yes

    - name: Install Zabbix agent
      yum:
        name: zabbix-agent
        state: present

    - name: Copy Zabbix agent configuration
      template:
        src: templates/zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
      notify:
        - restart zabbix-agent

  handlers:
    - name: restart zabbix-agent
      systemd:
        name: zabbix-agent
        state: restarted
