---
- name: Install Zabbix Agent and Register Host
  hosts: zabbix_hosts
  become: true

  tasks:
    - name: Install Zabbix Agent
      import_role:
        name: limepepper.zabbix-agent

    - name: Start Zabbix Agent
      service:
        name: zabbix-agent
        state: started
        enabled: yes

    - name: Create a new host for this agent
      community.zabbix.zabbix_host:
        login_user: Admin
        login_password: "zabbix"
        server_url: http://172.17.8.103:8080/
        host_name: "{{ inventory_hostname }}"
        host_groups: "{{ zabbix_groups }}"
        link_templates:
          - Template OS Linux
