---
- name: Create a new host or update an existing host's info
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Authenticate with Zabbix API
      zabbix_api:
        server_url: http://172.17.8.103:8080/
        login_user: Admin
        login_password: zabbix
      register: zabbix_auth

    - name: Use zabbix_host module to create/update host
      zabbix_host:
        zabbix_api_url: http://172.17.8.103:8080/
        zabbix_api_user: Admin
        zabbix_api_password: zabbix
        host_name: postgres.dev
        visible_name: postgres.dev
        description: My ExampleHost Description
        host_groups:
          - Linux servers
        link_templates:
          - Linux by Zabbix agent active
        status: enabled
        state: present
      when: zabbix_auth.success
