- name: Create a new host or update an existing host's info
  local_action:
    module: zabbix_host
    server_url: http://172.17.8.103:8080/
    login_user: Admin
    login_password: zabbix
    host_name: postgres.dev
    visible_name: postgres.dev
    description: My ExampleHost Description
    host_groups:
      - Linux servers
    link_templates:
      - Linux by Zabbix agent active
    status: enabled
    state: present